language: php
php:
  - 5.5
  - 5.6

mysql:
  database: travis_ci_drupal_module_example_test
  username: root
  encoding: utf8

install:
  - travis_retry composer self-update && composer update nothing && composer --version
  - travis_retry composer global require fxp/composer-asset-plugin --no-plugins
  - composer install --prefer-source --no-interaction --dev
  - echo 'xdebug.max_nesting_level=600' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS walle DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - ./yii migrate/up  --interactive=0

script:
  - find ./ -path './vendor' -prune -o -type f -iname "*.php" -print0 | xargs -0 -n1 php -l
matrix:
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
